apiVersion: v1
kind: ConfigMap
metadata:
  name: k8up-backup-mtls-env
  namespace: k8up-e2e-subject
data:
  CA_CERT_FILE: /mnt/tls/ca.crt
  CLIENT_CERT_FILE: /mnt/tls/tls.crt
  CLIENT_KEY_FILE: /mnt/tls/tls.key